name: Portfolio CI/CD

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: cd portfolio.web && npm i

      - name: Build project
        run: cd portfolio.web && npm run build

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          echo ${{ secrets.NETLIFY_SITE_ID }}
          echo ${{ secrets.NETLIFY_AUTH_TOKEN }}
          
          cd portfolio.web && netlify deploy \
            --dir dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
