name: Deploy website

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Install Netlify
        run: npm install netlify-cli@latest -g

      - name: Install Dependencies
        run: cd /portfolio.web && npm ci

      - name: Build project
        run: cd /portfolio.web && npm run build

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir /portfolio.web/dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}