name: Portfolio CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  deploy:
      name: 'Deploy to Netlify'
      runs-on: ubuntu-latest
      steps:
        - uses: jsmrcaga/action-netlify-deploy@v2.0.0
          with:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            NETLIFY_DEPLOY_TO_PROD: true
            NETLIFY_DEPLOY_MESSAGE: "Deployed from GitHub action"
            build_command: "cd /portfolio.web && npm run build"
            build_directory: "/portfolio.web/dist"